export const ALL_ORDERITEM_REQUEST = "ALL_ORDERS_REQUEST";
export const ALL_ORDERITEM_SUCCESS = "ALL_ORDERS_SUCCESS";
export const ALL_ORDERITEM_FAIL = "ALL_ORDERS_FAIL";

export const ORDERITEM_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDERITEM_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDERITEM_DETAILS_FAIL = "ORDER_DETAILS_FAIL";

export const CREATE_ORDERITEM_REQUEST = "CREATE_ORDERITEM_REQUEST";
export const CREATE_ORDERITEM_SUCCESS = "CREATE_ORDERITEM_SUCCESS";
export const CREATE_ORDERITEM_FAIL = "CREATE_ORDERITEM_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";