export const CREATE_PAYMENT_REQUEST = "CREATE_PAYMENT_REQUEST";
export const CREATE_PAYMENT_SUCCESS = "CREATE_PAYMENT_SUCCESS";
export const CREATE_PAYMENT_FAIL = "CREATE_PAYMENT_FAIL";

export const ALL_PAYMENT_REQUEST="ALL_PAYMENT_REQUEST"
export const ALL_PAYMENT_SUCCESS="ALL_PAYMENT_SUCCESS"
export const ALL_PAYMENT_FAIL="ALL_PAYMENT_FAIL"

export const PAYMENT_DETAILS_REQUEST = "PAYMENT_DETAILS_REQUEST";
export const PAYMENT_DETAILS_SUCCESS = "PAYMENT_DETAILS_SUCCESS";
export const PAYMENT_DETAILS_FAIL = "PAYMENT_DETAILS_FAIL";

export const CLEAR_ERRORS= "CLEAR_ERRORS"